server:
  port: 9001

jwt:
  secret-key: 4Ixa3PT4KhLW1fz4bJoY8z2dR4Gk7jHpB3Yw8mQvL9NdXx5vT9Yw8VhN3rB4YxK2

spring:
  application:
    name: repick-comment
  datasource:
    url: jdbc:mysql://localhost:3311/repick-comment?serverTimezone=Asia/Seoul
    username: dev
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379